language: java
jdk:
    - oraclejdk8

sudo: false
branches:
  only:
    - master
cache:
  directories:
  - "$HOME/.gradle"
before_install:
- chmod +x gradlew
script:
- "./gradlew clean build -x test"
#- "./gradlew :redcloud-eureka:bootRun"