spring:
  profiles:
    active: dev

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://test.toutiao.im:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: demo-provider
  profiles: test

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: demo-provider
  profiles: dev
