spring:
  profiles:
    active: dev

---
spring:
  profiles: test
server:
  port: 8761

eureka:
  instance:
    hostname: test.toutiao.im
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://test.toutiao.im:8761/eureka/

---
spring:
  profiles: dev
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/